version: '3'

services:
  mysql:
    image: mysql:5.7
    container_name: mysql_sonarqube
    environment:
      MYSQL_ROOT_PASSWORD: your_root_password
      MYSQL_USER: sonar
      MYSQL_PASSWORD: sonar_password
      MYSQL_DATABASE: sonar
    volumes:
      - mysql_data:/var/lib/mysql
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  sonarqube-db-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  mysql_data: