version: '3'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_USER: sonar
      MYSQL_PASSWORD: sonar_password
      MYSQL_DATABASE: sonar
    ports:
      - "3306:3306"

volumes:
  sonarqube-db-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
