version: '3.1'
services:
  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - "8200:8200"
      # Change   this to the following if you have reverse proxy setup
      #- "127.0.0.1:8200:8200"
    volumes:
      - ./config.hcl:/vault/config/config.hcl:ro
      - ./vault_data:/vault/data
    cap_add:
      - IPC_LOCK
    command: sh -c 'openssl req -x509 -newkey rsa:4096 -keyout /vault/key.pem -out /vault/certificate.pem -sha256 -days 3650 -nodes -subj "/ST=ISO_Server/L=ISO_Server/O=ISO_Server/OU=ISO_Server" && server'
    environment:
      - TZ=Europe/Berlin
    restart: always