version: '3.8'

services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    ports:
      - "8200:8200" # Port utilisé par Vault
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=root-token # Ceci est un token de développement, NE PAS UTILISER EN PRODUCTION
    volumes:
      - ./data:/vault/data # Volume pour persister les données Vault
    command: server -dev -dev-root-token-id=root-token -log-level=debug # Mode développement

  initialize-vault:
    image: hashicorp/vault:latest
    container_name: initialize-vault
    depends_on:
      - vault
    environment:
      - VAULT_ADDR=http://vault:8200
      - VAULT_TOKEN=root-token # Token de développement
    command: >
      sh -c "
      
        sleep 10 && # Attendre que Vault démarre
        vault operator init -key-shares=1 -key-threshold=1 &&
        vault login root-token &&
        vault secrets enable -path=mysecrets kv &&
        vault kv put mysecrets/mysecretkey myvalue=mysecretvalue
      "