version: '3.1'
services:
  vault:
    image: hashicorp/vault
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./config.hcl:/vault/config/config.hcl:ro
      - ./vault_data:/vault_data/
    #cap_add:
     # - IPC_LOCK
    command: server
    environment:
      - TZ=Europe/Berlin
    restart: always