version: '3.6'
services:
  vault:
    image: hashicorp/vault:latest
    container_name: vault
    restart: on-failure:10
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8200'
      VAULT_SKIP_VERIFY: true
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault-data:/vault-data
    healthcheck:
      retries: 5
    entrypoint: vault server -config=./vault-data/vault.hcl