version: '3.6'
services:
  vault:
    image: harshicorp/vault:latest
    container_name: vault
    restart: on-failure:10
    ports:
      - "8200:8200"
    environment:
      VAULT_ADDR: 'https://0.0.0.0:8200'
      VAULT_LOCAL_CONFIG: '{"listener": [{"tcp":{"address": "0.0.0.0:8200","tls_disable":"0", "tls_cert_file":"/vault-data/certificate.pem", "tls_key_file":"/vault-data/key.pem"}}], "default_lease_ttl": "168h", "max_lease_ttl": "720h"}, "ui": true}'
    cap_add:
      - IPC_LOCK
    volumes:
      - vault-data:/vault-data
    healthcheck:
      retries: 5
    command: /vault-data/workflow-vault.sh