version: '3.1'
services:
  vault:
    build:
      dockerfile: Dockerfile
    container_name: vault
    ports:
      - "8200:8200"
    volumes:
      - ./config.hcl:/vault/config/config.hcl:ro
    cap_add:
     - IPC_LOCK
    restart: always